api:
  endpoint: http://localhost/icuc_ars/api
  hash: a1ce5de4e28d18d580c21f65326b31e923842a97e273d79333ef80a1e67b3efd
attendance_settings:
  check_in_time: 07:00
  check_out_time: '18:00'
storage:
  donwloaded_images_dir: images
